# Generated by Django 4.2.16 on 2024-11-04 00:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('borrowed', 'US borrowed'), ('lent', 'lent')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'deleted'), ('waiting', 'waiting'), ('done', 'done')], max_length=20)),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('uzs', 'uzs'), ('rub', 'rub')], max_length=20)),
                ('whom', models.CharField(max_length=13)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-id'],
            },
        ),
    ]
