# Generated by Django 4.2.16 on 2024-11-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
